### ISSUE TITLE
VS2015 - apache cordova tools - button add exist items as link DISABLED!!!

### ISSUE THREAD

**Issue by gmorra** [squaredinfinity/VSCommands#3]
After installing vs2015 , create a solution apache cordova blank type , this solution I have 2 projects one base and the other items that inherits from the first project . But I find that when trying to add an existing item the Add button in the dialog box is no longer a dropdown -list but it is a button with the function to add, making it impossible for me to add items link type . as I can do to add existing elements as a link and not the physical item .

In VS2013CTP3 versions VS2015RC and I did not pass this, this happens to me now with VS2015

please help me!

**Comment by maroy1986** [comment]
I don't think your question is VSCommand related. This is not a support forum for VS2015 here...

Sorry, don't want to be rude, just making thinks clear.
