### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by gandarez** [squaredinfinity/VSCommands#4]
Hi,

Thanks for opening the source code with us! 
I just forked and hit build unsuccessfully. Also few references are missing.

![image](https://cloud.githubusercontent.com/assets/782854/11346264/e2869d14-9202-11e5-94c3-a34773016601.png)

**Comment by squaredinfinity** [comment]
Hi!
I think missing packages were not yet indexed by nuget.org, they should be online now.

**Comment by gandarez** [comment]
@squaredinfinity it's missing app.config from Presentation.vs14 project.
![image](https://cloud.githubusercontent.com/assets/782854/11365250/5115dd24-928c-11e5-92c1-fc0ad163a791.png)

**Comment by squaredinfinity** [comment]
Damn, sorry for that.
Don't think it's needed anyway.
I'll look into that tonight.

Thanks!

Sent from my Windows Phone

**Comment by gandarez** [comment]
Thanks in advance @squaredinfinity

**Comment by gandarez** [comment]
@squaredinfinity any news?

**Comment by mgmoody42** [comment]
@gandarez adding an empty app.config file and re-compile is successful for me.
